[versions]
kotlin = "2.1.21"
dokka = "2.0.0"
vanniktech = "0.34.0"
jsoup = "1.16.1"
junit = "5.8.2"

[libraries]
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }